[package]
name = "flasherd"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
log = "0.4.27"
simplelog = "0.12.2"
tokio = { version = "1.46.1", features = ["macros", "net", "rt", "rt-multi-thread"] }
